export const presets = [
  // Acoustic Pianos:
  {
    cc: 104,
    ioff: 0,
    name: 'Ant. Petrof',
    presets: [
      'Ant. Petrof Prelude',
      'Ant. Petrof Warm',
      'Ant. Petrof Venue',
      'Ant. Petrof 275',
      'Ant. Petrof Recording 1',
      'Ant. Petrof Recording 2',
      'Ant. Petrof Recording 3',
      'Ant. Petrof Cinematic',
      'Ant. Petrof Bass & Piano split',
      'Ant. Petrof Intimate',
      'Ant. Petrof Player',
      'Ant. Petrof Under Lid',
      'Ant. Petrof Duo',
      'Ant. Petrof Dreamy',
      'Ant. Petrof Cosmic',
      'Ant. Petrof Broken',
    ]
  },
  {
    cc: 104,
    ioff: 20, // added to index of preset
    name: 'Petrof Mistral',
    presets: [
      'Petrof Mistral Prelude',
      'Petrof Mistral Warm',
      'Petrof Mistral Venue',
      'Petrof Mistral 284',
      'Petrof Mistral Classical Recording',
      'Petrof Mistral Jazz Recording',
      'Petrof Mistral Cinematic',
      'Petrof Mistral Bass & Piano split',
      'Petrof Mistral Intimate',
      'Petrof Mistral Player',
      'Petrof Mistral Under Lid',
      'Petrof Mistral Gentle',
      'Petrof Mistral Dreamy',
      'Petrof Mistral Cosmic',
      'Petrof Mistral Broken',
    ]
  },
  {
    cc: 102,
    ioff: 0,
    name: 'Bluethner',
    presets: [
      'Bluethner Prelude',
      'Bluethner Home',
      'Bluethner Model One BA',
      'Bluethner Model One AB',
      'Bluethner Studio Recording BA',
      'Bluethner Studio Recording AB',
      'Bluethner Chamber Recording BA',
      'Bluethner Chamber Recording AB',
      'Bluethner Concert Recording BA',
      'Bluethner Concert Recording AB',
      'Bluethner Cinematic',
      'Bluethner Player',
      'Bluethner Intimate',
    ],
  },
  {
    cc: 103,
    ioff: 0,
    name: 'C. Bechstein DG',
    presets: [
      'C. Bechstein DG Prelude',
      'C. Bechstein DG Sweet',
      'C. Bechstein DG D 282',
      'C. Bechstein DG Recording 1',
      'C. Bechstein DG Recording 2',
      'C. Bechstein DG Recording 3',
      'C. Bechstein DG Cinematic',
      'C. Bechstein DG Snappy',
      'C. Bechstein DG Bass & Piano split',
      'C. Bechstein DG Venue',
      'C. Bechstein DG Player',
      'C. Bechstein DG Under Lid',
      'C. Bechstein DG Cosmic',
      'C. Bechstein DG Broken',
    ],
  },
]
