export const presets = [
  // Acoustic Pianos:
  {
    cc: 104,
    name: 'Ant. Petrof',
    presets: [
      'Ant. Petrof Prelude',
      'Ant. Petrof Warm',
      'Ant. Petrof Venue',
      'Ant. Petrof 275',
      'Ant. Petrof Recording 1',
      'Ant. Petrof Recording 2',
      'Ant. Petrof Recording 3',
      'Ant. Petrof Cinematic',
      'Ant. Petrof Bass & Piano split',
      'Ant. Petrof Intimate',
      'Ant. Petrof Player',
      'Ant. Petrof Under Lid',
      'Ant. Petrof Duo',
      'Ant. Petrof Dreamy',
      'Ant. Petrof Cosmic',
      'Ant. Petrof Broken',
    ]
  },
  {
    cc: 102,
    name: 'Bluethner',
    presets: [
      'Bluethner Prelude',
      'Bluethner Home',
      'Bluethner Model One BA',
      'Bluethner Model One AB',
      'Bluethner Studio Recording BA',
      'Bluethner Studio Recording AB',
      'Bluethner Chamber Recording BA',
      'Bluethner Chamber Recording AB',
      'Bluethner Concert Recording BA',
      'Bluethner Concert Recording AB',
      'Bluethner Cinematic',
      'Bluethner Player',
      'Bluethner Intimate',
    ],
  },
  {
    cc: 103,
    name: 'C. Bechstein DG',
    presets: [
      'C. Bechstein DG Prelude',
      'C. Bechstein DG Sweet',
      'C. Bechstein DG D 282',
      'C. Bechstein DG Recording 1',
      'C. Bechstein DG Recording 2',
      'C. Bechstein DG Recording 3',
      'C. Bechstein DG Cinematic',
      'C. Bechstein DG Snappy',
      'C. Bechstein DG Bass & Piano split',
      'C. Bechstein DG Venue',
      'C. Bechstein DG Player',
      'C. Bechstein DG Under Lid',
      'C. Bechstein DG Cosmic',
      'C. Bechstein DG Broken',
    ],
  },
]
