export const presets = [
  // Acoustic Pianos:
  // (CC 102-119 udnefined by MIDI standart)
  {
    cc: 104,
    ioff: 0,
    name: 'Ant. Petrof',
    presets: [
      'Ant. Petrof Prelude',
      'Ant. Petrof Warm',
      'Ant. Petrof Venue',
      'Ant. Petrof 275',
      'Ant. Petrof Recording 1',
      'Ant. Petrof Recording 2',
      'Ant. Petrof Recording 3',
      'Ant. Petrof Cinematic',
      'Ant. Petrof Bass & Piano split',
      'Ant. Petrof Intimate',
      'Ant. Petrof Player',
      'Ant. Petrof Under Lid',
      'Ant. Petrof Duo',
      'Ant. Petrof Dreamy',
      'Ant. Petrof Cosmic',
      'Ant. Petrof Broken',
    ]
  },
  {
    cc: 104,
    ioff: 20, // added to index of preset
    name: 'Petrof Mistral',
    presets: [
      'Petrof Mistral Prelude',
      'Petrof Mistral Warm',
      'Petrof Mistral Venue',
      'Petrof Mistral 284',
      'Petrof Mistral Classical Recording',
      'Petrof Mistral Jazz Recording',
      'Petrof Mistral Cinematic',
      'Petrof Mistral Bass & Piano split',
      'Petrof Mistral Intimate',
      'Petrof Mistral Player',
      'Petrof Mistral Under Lid',
      'Petrof Mistral Gentle',
      'Petrof Mistral Dreamy',
      'Petrof Mistral Cosmic',
      'Petrof Mistral Broken',
    ]
  },
  {
    cc: 102,
    ioff: 0,
    name: 'Bluethner',
    presets: [
      'Bluethner Prelude',
      'Bluethner Improv',
      'Bluethner Model One',
      'Bluethner Model One AB',
      'Bluethner Studio Recording BA',
      'Bluethner Studio Recording AB',
      'Bluethner Chamber Recording BA',
      'Bluethner Chamber Recording AB',
      'Bluethner Concert Recording BA',
      'Bluethner Concert Recording AB',
      'Bluethner Cinematic',
      'Bluethner Player',
      'Bluethner Intimate',
    ],
  },
  {
    cc: 103,
    ioff: 0,
    name: 'C. Bechstein DG',
    presets: [
      'C. Bechstein DG Prelude',
      'C. Bechstein DG Sweet',
      'C. Bechstein DG D 282',
      'C. Bechstein DG Recording 1',
      'C. Bechstein DG Recording 2',
      'C. Bechstein DG Recording 3',
      'C. Bechstein DG Cinematic',
      'C. Bechstein DG Snappy',
      'C. Bechstein DG Bass & Piano split',
      'C. Bechstein DG Venue',
      'C. Bechstein DG Player',
      'C. Bechstein DG Under Lid',
      'C. Bechstein DG Cosmic',
      'C. Bechstein DG Broken',
    ],
  },
  {
    cc: 105,
    ioff: 0,
    name: 'Other Pianos',
    presets: [
      'Erard (1992) Close Mic',
      'Erard (1992) Player',
      'Erard (1992) Recording',
      'Pleyel (1926) Close Mic',
      'Pleyel (1926) Player',
      'Pleyel (1926) Recording',
      'CP-80 Line Output',
      'CP-80 Tremolo',
      'CP-80 Amped',
      'CP-80 Recording',
      'CP-80 SoundBoarded',
    ],
  },
  {
    cc: 106,
    ioff: 0,
    name: 'Historical',
    presets: [
      'J. Schantz (1790)',
      'J. Schantz 415',
      'J. Schantz 415 Player',
      'J. Schantz 415 Recording',
      'J. Schantz 392',

      'J.E. Schmidt (1790)',
      'J.E. Schmidt 415',
      'J.E. Schmidt 415 Player',
      'J.E. Schmidt 415 Recording',
      'J.E. Schmidt 392',

      'A. Walter (1790)',
      'A. Walter 415',
      'A. Walter 415 Player',
      'A. Walter 415 Recording',
      'A. Walter 392',
      'D. Schöffstoss (1812)',
      'D. Schöffstoss 415',
      'D. Schöffstoss 415 Player',
      'D. Schöffstoss 415 Recording',
      'D. Schöffstoss 392',

      'C. Graf (1826)',
      'C. Graf 415',
      'C. Graf 415 Player',
      'C. Graf 415 Recording',
      'C. Graf 392',
    ],
  },
  {
    cc: 107,
    ioff: 0,
    name: 'Predecessor',
    presets: [
      'Cimbalom Basic',
      'Cimbalom Hard',
      'Cimbalom Soft',
      'Cimbalom à la piano',
      'Cimbalom Tzigane',
      'Cimbalom 415',
      'Cimbalom 392',

      'Clavichord single',
      'Clavichord double',
      'Clavichord lute',
      'Clavichord 415',
      'Clavichord 392',

      'Harpschrd. F.E. Blanchet (1733)',
      'Harpschrd. F.E. Blanchet 415',
      'Harpschrd. F.E. Blanchet 392',

      'Harpschrd. C. Grimaldi A (1697)',
      'Harpschrd. C. Grimaldi A 415',
      'Harpschrd. C. Grimaldi A 392',

      'Harpschrd. C. Grimaldi B',
      'Harpschrd. C. Grimaldi B 415',
      'Harpschrd. C. Grimaldi B 392',
      
      'Harpschrd. C. Grimaldi A+B',
      'Harpschrd. C. Grimaldi A+B 415',
      'Harpschrd. C. Grimaldi A+B 392',
    ],
  },
  {
    cc: 108,
    ioff: 0,
    name: 'Bells',
    presets: [
      'Church - Original',
      'Bell-the-fly',
      'Church - soft clapper',
      'Church - tremolo',
      'Church - sustain',
      'Tubular - original',
      'Tubular - major',
      'Tubular - minor',
    ],
  },
]
